default: pdf

pdf: 
	pdflatex Thesis_Proposal.tex 
	pdflatex Thesis_Proposal.tex

clean:
	rm -f *.bbl *.blg *.ps *.dvi *.aux *.toc *.idx *.ind *.ilg *.log *.out *.nav *.snm *.synctex.gz *.lof *.lot *-blx.bib *.fdb_latexmk *.fls *.loa *.vrb
